//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deudas.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargos_deudas
    {
        public int idcargo { get; set; }
        public Nullable<int> iddeuda { get; set; }
        public int idusuario { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<System.DateTime> fechahoracargo { get; set; }
    
        public virtual deudas deudas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
