//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deudas.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class deudas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deudas()
        {
            this.abonos_deuda = new HashSet<abonos_deuda>();
            this.cargos_deudas = new HashSet<cargos_deudas>();
        }
    
        public int iddeuda { get; set; }
        public string nombreDeuda { get; set; }
        public byte estatus { get; set; }
        public Nullable<short> dia_corte { get; set; }
        public Nullable<int> dia_limite_pago { get; set; }
        public System.DateTime fechaalta { get; set; }
        public System.TimeSpan horaalta { get; set; }
        public int idusuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abonos_deuda> abonos_deuda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargos_deudas> cargos_deudas { get; set; }
        public virtual detalle_deuda detalle_deuda { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
