//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deudas.DAL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class deudasEntities : DbContext
    {
        public deudasEntities()
            : base("name=deudasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abonos_deuda> abonos_deuda { get; set; }
        public virtual DbSet<cargos_deudas> cargos_deudas { get; set; }
        public virtual DbSet<detalle_deuda> detalle_deuda { get; set; }
        public virtual DbSet<deudas> deudas { get; set; }
        public virtual DbSet<ingresos> ingresos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<gastos> gastos { get; set; }
    }
}
