/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package deudas;

import deudas.clases.gasto;
import deudas.clases.ingreso;
import deudas.modelo.ingresosModelo;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mdominguez
 */
public final class gastos extends javax.swing.JFrame {

    /**
     * Creates new form gastos
     */
    public gastos() throws SQLException {
        super("Registro de gastos");
        initComponents();
        //centra la ventana
        setLocationRelativeTo(getRootPane());
        cargaComboIngresos();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbIngresos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtCantidadGasto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardarGasto = new javax.swing.JButton();
        btnSalirGastos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtNombreGasto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona ingreso");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad");

        btnGuardarGasto.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnGuardarGasto.setText("Guardar");
        btnGuardarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarGastoActionPerformed(evt);
            }
        });

        btnSalirGastos.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btnSalirGastos.setText("Salir");
        btnSalirGastos.setToolTipText("");
        btnSalirGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirGastosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Droid Sans Fallback", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registro de gastos");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Observaciones");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nombre gasto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnGuardarGasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIngresos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreGasto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadGasto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(txtNombreGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCantidadGasto, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarGasto)
                    .addComponent(btnSalirGastos))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarGastoActionPerformed
        ingresosModelo objIngresos = (ingresosModelo) cmbIngresos.getSelectedItem();
        if (objIngresos.getIdingreso() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un ingreso", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                List<ingresosModelo> objIngresoPorId = null;
                double ingresoActual = 0.0;
                try {
                    objIngresoPorId = new ingreso().consultaIngresosPorID(objIngresos.getIdingreso());
                    if (objIngresoPorId.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No se puede tomar saldo de este ingreso", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        //Obtiene la cantidad del ingreso seleccionado
                        ingresoActual = objIngresoPorId.get(0).getCantidad_actual();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(pagos.class.getName()).log(Level.SEVERE, null, ex);
                }
                double gasto = Double.parseDouble(txtCantidadGasto.getText().trim());
                //Comparar si la cantidad actual es mayor o igual que el ingreso actual
                if (ingresoActual >= gasto) {
                    try {
                        String observaciones = txtObservaciones.getText().trim();
                        String nombre = txtNombreGasto.getText().trim();
                        if ("".equals(nombre)) {
                            JOptionPane.showMessageDialog(this, "El campo nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            String res = new gasto().insertaGasto(gasto,objIngresos.getIdingreso(), nombre, observaciones);

                            if ("ok".equals(res)) {
                                JOptionPane.showMessageDialog(this, "Se ha insertado el gasto con éxito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                                txtCantidadGasto.setText("");
                                txtNombreGasto.setText("");
                                txtObservaciones.setText("");
                                //principal.txtPanelInformacion.setText("Hola");
                                principal.cargaDatosFooter();
                                //cargaCombo();
                                cargaComboIngresos();
                            } else {
                                JOptionPane.showMessageDialog(this, res, "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(pagos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "La cantidad que se desea abonar supera el limite actual del ingreso que es " + ingresoActual, "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Favor de capturar solo numeros", "Aviso", JOptionPane.ERROR_MESSAGE);
                txtCantidadGasto.setFocusable(true);
            }
        }
    }//GEN-LAST:event_btnGuardarGastoActionPerformed

    private void btnSalirGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirGastosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirGastosActionPerformed

//    public void cargaCombo() throws SQLException {
//        List<deudaModelo> lista = new deuda().consultaDeuda();
//        cmbIngresos.removeAllItems();
//        if (lista == null || lista.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "No se han encontrado deudas activas aún");
//            cmbIngresos.repaint();
//        }else{
//            for(deudaModelo dm : lista){
//                cmbIngresos.addItem((deudaModelo) dm);
//            }
//            cmbIngresos.repaint();
//        }
//    }
    public void cargaComboIngresos() throws SQLException {
        cmbIngresos.removeAllItems();
        List<ingresosModelo> lista = new ingreso().consultaIngresos();
        ingresosModelo dm1 = new ingresosModelo("Selecciona una opcion", -1);
        cmbIngresos.addItem(dm1);
        if (lista == null || lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se han encontrado ingresos activos aún");
            cmbIngresos.repaint();
        } else {
            for (ingresosModelo dm : lista) {
                cmbIngresos.addItem(dm);
            }
            cmbIngresos.repaint();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new gastos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(gastos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarGasto;
    private javax.swing.JButton btnSalirGastos;
    private javax.swing.JComboBox cmbIngresos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidadGasto;
    private javax.swing.JTextField txtNombreGasto;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
