/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package deudas;

import deudas.clases.abonos;
import deudas.clases.deuda;
import deudas.clases.ingreso;
import deudas.modelo.deudaModelo;
import deudas.modelo.ingresosModelo;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mdominguez
 */
public class pagos extends javax.swing.JFrame {

    /**
     * Creates new form pagos
     */
    public pagos() throws SQLException {
        super("Registro de nuevo pago");
        initComponents();
        //centra la ventana
        setLocationRelativeTo(getRootPane());
        cargaCombo();
        cargaComboIngresos();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    public void cargaCombo() throws SQLException {
        cmbDeudas.removeAllItems();
        List<deudaModelo> lista = new deuda().consultaDeudaConAdeudo();
        deudaModelo dm1 = new deudaModelo("Selecciona una opcion", -1);
        cmbDeudas.addItem(dm1);
        if (lista == null || lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se han encontrado deudas activas aún");
            cmbDeudas.repaint();
        } else {
            for (deudaModelo dm : lista) {
                cmbDeudas.addItem(dm);
            }
            cmbDeudas.repaint();
        }
    }

    public void cargaComboIngresos() throws SQLException {
        cmbIngresos.removeAllItems();
        List<ingresosModelo> lista = new ingreso().consultaIngresos();
        ingresosModelo dm1 = new ingresosModelo("Selecciona una opcion", -1);
        cmbIngresos.addItem(dm1);
        if (lista == null || lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se han encontrado ingresos activos aún");
            cmbIngresos.repaint();
        } else {
            for (ingresosModelo dm : lista) {
                cmbIngresos.addItem(dm);
            }
            cmbIngresos.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbDeudas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbIngresos = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtSeDebe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAAbonoDinero = new javax.swing.JTextField();
        btnGuardarPago = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setText("Deuda");

        cmbDeudas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDeudasItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Ingreso");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setText("Se debe");

        txtSeDebe.setEditable(false);
        txtSeDebe.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel4.setText("Abono $");

        btnGuardarPago.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        btnGuardarPago.setText("Guardar");
        btnGuardarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPagoActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Droid Sans Fallback", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registro de pagos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbIngresos, 0, 176, Short.MAX_VALUE)
                            .addComponent(cmbDeudas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSeDebe)
                            .addComponent(txtAAbonoDinero)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnGuardarPago)
                        .addGap(67, 67, 67)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeDebe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAAbonoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPago)
                    .addComponent(btnSalir))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPagoActionPerformed
        // TODO add your handling code here:
        deudaModelo objDeudas = (deudaModelo) cmbDeudas.getSelectedItem();
        ingresosModelo objIngresos = (ingresosModelo) cmbIngresos.getSelectedItem();
        if (objDeudas.getIddeuda() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una deuda", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (objIngresos.getIdingreso() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un ingreso", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                List<ingresosModelo> objIngresoPorId = null;
                double ingresoActual = 0.0;
                try {
                    objIngresoPorId = new ingreso().consultaIngresosPorID(objIngresos.getIdingreso());
                    if (objIngresoPorId.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No se puede tomar saldo de este ingreso", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        //Obtiene la cantidad del ingreso seleccionado
                        ingresoActual = objIngresoPorId.get(0).getCantidad_actual();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(pagos.class.getName()).log(Level.SEVERE, null, ex);
                }
                double abono = Double.parseDouble(txtAAbonoDinero.getText().trim());
                //Comparar si la cantidad actual es mayor o igual que el ingreso actual
                if (ingresoActual >= abono) {
                    try {
                        //Falta hacer que se descuente la cantidad del ingreso, y de detalle_deuda
                        String res = new abonos().insertaAbono(abono, objDeudas.getIddeuda(), objIngresos.getIdingreso(), ingresoActual);
                        
                        if ("ok".equals(res)) {
                            JOptionPane.showMessageDialog(this, "Se ha insertado el ingreso con éxito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                            txtAAbonoDinero.setText("");
                            txtSeDebe.setText("");
                            //principal.txtPanelInformacion.setText("Hola");
                            principal.cargaDatosFooter();
                            //cargaCombo();
                            cargaComboIngresos();
                        } else {
                            JOptionPane.showMessageDialog(this, res, "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(pagos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "La cantidad que se desea abonar supera el limite actual del ingreso que es "+ingresoActual, "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Favor de capturar solo numeros", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarPagoActionPerformed

    private void cmbDeudasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDeudasItemStateChanged
        // TODO add your handling code here:
        deudaModelo objDeudas = (deudaModelo) cmbDeudas.getSelectedItem();
        try {
            if (objDeudas.getIddeuda() == -1) {
                txtSeDebe.setText("");
            } else {
                double monto = new deuda().obtieneMonto(objDeudas.getIddeuda());
                txtSeDebe.setText(String.valueOf(monto));
            }
        } catch (SQLException ex) {
            Logger.getLogger(pagos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbDeudasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pagos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(pagos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarPago;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbDeudas;
    private javax.swing.JComboBox cmbIngresos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAAbonoDinero;
    private javax.swing.JTextField txtSeDebe;
    // End of variables declaration//GEN-END:variables
}
